export class APIConstant{
    public static BaseAPI="http://localhost:4000/api/"
    public static getAllProject=APIConstant.BaseAPI+"projectlist"
    public static saveProject=APIConstant.BaseAPI+"projectadd"
    public static deleteProject=APIConstant.BaseAPI+"projectdelete"
    public static getAllApps=APIConstant.BaseAPI+"getApps"
    public static ADD_ATTENDENCE=APIConstant.BaseAPI+"addAttendence"
    public static GET_ATTENDENCE=APIConstant.BaseAPI+"getAttendence"
    public static UPDATE_ATTENDENCE=APIConstant.BaseAPI+"updateAttendence"
    public static CREATE_PLANNER=APIConstant.BaseAPI+"createPlanner"
    public static GET_PLANNER=APIConstant.BaseAPI+"getPlanner"
    public static GET_SINGLE_PLAN=APIConstant.BaseAPI+"getSinglePlan"
    public static CREATE_CONTAINER=APIConstant.BaseAPI+"createContainer"
    public static GET_PLAN_CONTAINER=APIConstant.BaseAPI+"getPlanContainer"
    public static GET_TASK_CONTAINER=APIConstant.BaseAPI+"getTaskContainer"
    public static ADD_TASK=APIConstant.BaseAPI+"addTask"
    public static DELETE_CONTAINER=APIConstant.BaseAPI+"delteContainer"
    public static ADD_REPOSITORY=APIConstant.BaseAPI+"addRepository"
    public static GET_REPOSITORY=APIConstant.BaseAPI+"getRepository"

}